name: Publish Development Version

on:
    push: 
        branches:
            - dev

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
    
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with: 
            node-version: 20
            registry-url: https://registry.npmjs.org/

        - name: Install Dependencies
          run: npm ci

        - name: Bump The Version (Using Commit Hash)
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            CURRENT_VERSION=$(npm pkg get version | tr -d '"')
            BASE_VERSION=$(echo "$CURRENT_VERSION" | sed 's/-.*//')
            COMMIT_HASH=$(git rev-parse --short HEAD)
            NEW_VERSION="${BASE_VERSION}-dev.${COMMIT_HASH}"
            npm version --no-git-tag-version $NEW_VERSION
            echo "Success"
        
        - name: "Publish To NPM (dev)"
          run: npm publish --access public --tag dev
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}